{% set name = "mlcroissant" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlcroissant-{{ version }}.tar.gz
  sha256: 0f102206da26fef33ca10614dc7a969965b8c7e9bfa8b65db90b7c0ca60e3bdc

build:
  entry_points:
    - mlcroissant = mlcroissant.scripts.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - absl-py
    - etils >=1.7.0
    - jsonpath-rw
    - networkx
    - pandas
    - pandas-stubs
    - python-dateutil
    - rdflib
    - requests
    - tqdm
    - typing_extensions
    - importlib_resources

test:
  imports:
    - mlcroissant
  commands:
    - pip check
  requires:
    - pip

about:
  summary: MLCommons datasets format.
  home: https://github.com/mlcommons/croissant
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
